codeit-moving/moving-be

- src/controllers/moverController.ts
- src/controllers/movingRequestController.ts
- src/middlewares/errorHandler.ts
- src/middlewares/validations/movingRequest.ts
- src/repositorys/moverRepository.ts
- src/repositorys/movingRequestRepository.ts
- src/repositorys/quoteRepository.ts
- src/services/moverService.ts
- src/services/movingRequestService.ts
- src/utils/checkBoolean.ts
- src/utils/interfaces/mover/ratingResult.ts
- src/utils/interfaces/movingRequest/movingRequest.ts
- src/utils/mover/getRatingsByMover.ts
- src/utils/processMoverData.ts
> [탁우현] mover and movingRequest 관련 로직 생성 

- prisma/migrations/20241202044806_update/migration.sql
- src/app.ts
- src/controllers/moverController.ts
- src/controllers/movingRequestController.ts
- src/controllers/quoteController.ts
- src/controllers/regionController.ts
- src/middlewares/errorHandler.ts
- src/middlewares/validations/movingRequest.ts
- src/repositorys/moverRepository.ts
- src/repositorys/movingRequestRepository.ts
- src/repositorys/quoteRepository.ts
- src/services/moverService.ts
- src/services/movingRequestService.ts
- src/services/quoteService.ts
- src/utils/interfaces/movingRequest/movingRequest.ts
- src/utils/mover/processMoverData.ts
- src/utils/processMoverData.ts
- src/utils/quote/processQuoteData.ts
1. 레포지토리 부분의 불필요한 필드값을 삭제했습니다.
2. 현재 로그인된 사용자의 활성 이사요청의 대기 중인 견적서 조회 기능을 추가 했습니다.
3. 사용자 기능 구현전의 고정된 customerId 값으로 테스틀 하였습니다.
> [ 탁우현 ] 20241203 

- prisma/ERD.md
- prisma/migrations/20241205002823_update_moving_requset/migration.sql
- prisma/schema.prisma
- src/controllers/movingRequestController.ts
- src/middlewares/validations/movingRequest.ts
- src/repositorys/movingRequestRepository.ts
- src/repositorys/quoteRepository.ts
- src/utils/interfaces/movingRequest/movingRequest.ts
- src/utils/quote/processQuoteData.ts
프리즈마 필드명 변경으로 
레포  pull 받은후 프리즈마 prisma 라이브러리 generate 해야 합니다!
해당 스키마 변경으로 인한 기존 로직의 데이터 명도 변경되었습니다.
> 🗃️ [스키마변경] : 단수 서비스

- src/controllers/moverController.ts
- src/repositorys/movingRequestRepository.ts
해당 Id의 movingRequest를 반환하는 repository 추가
> ✨ [기능추가] : movingRequest By Id

- package-lock.json
- src/controllers/moverController.ts
- src/repositorys/moverRepository.ts
- src/services/moverService.ts
- src/services/userService.ts
- src/utils/mover/processMoverData.ts
렌딩페이지 
기사의 마이페이지 조회의 사용될 API 
기사의 프로필과 각 필드값을 반환 한다
> [ 탁우현] 기사 -> 나의 프로필 조회

- src/controllers/movingRequestController.ts
- src/repositorys/movingRequestRepository.ts
- src/schedules/notifications.ts
- src/services/movingRequestService.ts
- node-cron을 활용한 알림 생성에서 address 문자열을 가공하여 생성
- node-cron 라이브러리를 활용한 스케줄러 작성
- 필요시 패키지설치 필요
- movingRequest 커서기반 엔드포인트명 변경
- / -> /my-mover
> [탁우현] 주소가공 및 프론트 요청사항 반영

- package-lock.json
- prisma/ERD.md
- prisma/migrations/20241219083653_update_moving_request/migration.sql
- src/controllers/movingRequestController.ts
- src/middlewares/validations/movingRequest.ts
- src/repositorys/movingRequestRepository.ts
- src/services/movingRequestService.ts
- src/utils/interfaces/movingRequest/movingRequest.ts
- 기존의 모든 데이터 조회를 이사일이 지난 데이터를 필터하는 isPastRequest query 추가
- 기본값은 false로 하며 true로 전달시 이사일이 지난 데이터도 조회
- 지난 요청에서 조건부 수정 
- 검색 조건과 별도로 분리하여 모든 레코드의 수를 반환
> [탁우현] 프론트 요청사항 반영

- src/controllers/moverController.ts
- src/repositorys/moverRepository.ts
- src/repositorys/movingRequestRepository.ts
- src/services/moverService.ts
- src/services/movingRequestService.ts
- src/utils/interfaces/mover/ratingResult.ts
- src/utils/mover/getRatingsByMover.ts
- 기존에 이미 지정한 기사라면 메시지 반환
- 지정한 기사가 아닌 것을 취소 하려면 메시지 반환
- 라우터 정의 순서의 오류가 있음 정의 순서 변경
- 찜한 기사 목록 조회에서 찜한 기사가 없다면 메시지 반환
> [탁우현] 기능개선 20241220 

- package-lock.json
- src/app.ts
- src/controllers/quoteController.ts
- src/controllers/reviewController.ts
- src/repositorys/quoteRepository.ts
- src/repositorys/reviewRepository.ts
- src/services/quoteService.ts
- src/services/reviewService.ts
- src/utils/review/types.ts
- review [강범준] : 기사의 리뷰 목록 조회
- (GET)
1. Endpoint : GET /reviews/mover/:moverId
2. Description : 기사의 리뷰 목록 조회
3. Request : accessToken
- 200 OK
1. Response : 
```tsx
{
"currentPage": 1,
"pageSize": 5,
"totalPages": 1,
"totalCount": 1,
"list": [
{
"id": 6,
"images": [
"www.codeit.com/rv2_image1.svg",
"www.codeit.com/rv2_image2.svg"
],
"name": "김철수",
"rating": 3,
"content": "책상에 파손 부분이 있습니다.",
"createdAt": "2024-12-17T08:35:17.524Z"
}
]
}
```
- review [강범준] : 내가 작성한 리뷰 목록 조회
- (GET)
1. Endpoint : GET /reviews/me
2. Description : 내가 작성한 리뷰 목록 조회
3. Request : 
- 200 OK
1. Response : 
```tsx
{
"currentPage": 1,
"totalPages": 1,
"totalCount": 1,
"list": [
{
"id": 6,
"service": 1,
"isDesignated": false,
"imageUrl": [],
"nickname": "박진우",
"movingDate": "2024-12-05T10:00:00.000Z",
"cost": 150000, …
```
> 기능구현 : (고객이)작성한 리뷰 목록 조회, 리뷰 목록 조회(기사 상세페이지용), 리뷰 생성하기

- data/mover.ts
- package.json
- src/controllers/moverController.ts
- src/controllers/movingRequestController.ts
- src/repositorys/moverRepository.ts
- src/services/moverService.ts
- src/services/movingRequestService.ts
- 기존의 토글 방식에서 http 메소드에 맞는 post/delete로 컨트롤러 및 로직 변경
- request query 수정
> [탁우현] 프론트 요청 기사 찜/취소 하기 로직 변경

- src/env.ts
- src/services/userService.ts
- src/typings/env.d.ts
이미지가 없을 경우 서비스에서 디폴트 이미지 넣어주도록 추가하였습니다.
> getUser 디폴트 이미지 추가

- src/config/cookie.config.ts
- src/controllers/oauthController.ts
> [안재민] 세션 쿠키옵션 변경

- src/controllers/confirmedQuoteController.ts
- src/controllers/moverController.ts
- src/controllers/movingRequestController.ts
- src/controllers/quoteController.ts
- src/env.ts
- src/middlewares/authMiddleware.ts
- src/typings/env.d.ts
- src/utils/interfaces/customError.ts
- 고객/기사 프로필이 등록되어 있지 않다면 리다이렉트 관련 리스폰스 반환하는 미들웨어 추가
- 일단 제가 작성한 엔드포인트만 추가 했습니다.
- 추후 각 엔드 포인트에 적용 부탁 드립니다.
> [탁우현] 프로필 등록 관련 리다이렉트

- src/controllers/authController.ts
- src/controllers/moverController.ts
- src/repositorys/userRepository.ts
- src/services/userService.ts
> [탁우현] 리프레쉬 토큰 페이로드 값 없음 문제 해결

- src/app.ts
- src/repositorys/movingRequestRepository.ts
- src/services/movingRequestService.ts
/by-mover 엔드포인트의 counts 조건부 변경 CROS url 추가
> ⚗️ [성능개선] : 프론트 요청사항 반영

- prisma/ERD.md
- prisma/migrations/20241230001548_/migration.sql
- prisma/schema.prisma
- src/controllers/oauthController.ts
- src/middlewares/passport.ts
- src/repositorys/userRepository.ts
- src/services/oauthService.ts
userType : customer | mover
- customer: "/me/profile"
- mover: "/mover/profile"
프론트엔드 배포된게 있다면 알려주세요. 소셜 어플리케이션 설정 리다이렉트url에 등록하겠습니다!
> [안재민] 유저타입 추가

- src/controllers/quoteController.ts
- src/controllers/reviewController.ts
- src/repositorys/quoteRepository.ts
- src/repositorys/reviewRepository.ts
- src/services/quoteService.ts
- src/services/reviewService.ts
- src/utils/review/types.ts
- quotes [강범준] : (기사님의)보낸 견적서 목록 조회
- /(GET)
1. Endpoint : GET /quotes/mover
2. Description : (기사님의)보낸 견적서 목록 조회
3. Reqeust : accessToken 
- 200 OK
1. Response : 
```tsx
{
"nextCursor": null,
"hasNext": false,
"list": [
{
"id": 1,
"service": 1,
"isDesignated": false,
"name": "김철수",
"movingDate": "2024-12-28T10:00:00.000Z",
"pickupAddress": "서울시 강남구",
"dropOffAddress": "서울시 송파구",
"cost": 580000,
"isCompleted": true,
"isConfirmed": false,
"requestDate": "2024-12-23T00:00:00.000Z"
},
```
- quotes [강범준] : (기사님의)견적서 상세 조회
- /(GET)
1. Endpoint : GET /quotes/mover/:quoteId
2. Description : (기사님의)견적서 상세 조회
3. Reqeust : accessToken 
- 200 OK
1. Response : 
```tsx
{
"id": 37,
"cost": 520000,
"comment": "대구 지역 이사 전문가입니다.",
"service": 2,
"customerName": "이수연",
"movingDate": …
```
> :recycle:[Refactor]프론트 요구사항 반영

- src/controllers/movingRequestController.ts
- src/repositorys/movingRequestRepository.ts
- src/services/confirmedQuoteService.ts
- src/services/movingRequestService.ts
-로그인한 사용자의 활성이사 요청을 확인하는 엔드포인트
-현재 movingDate가 현재 시간의 미래만 활성상태로 인식
-movingDate가 오늘 날짜 이면서 확정된 견적이 없다면 비 활성 상태
> [탁우현] 활성 이사요청 조건부 수정

- src/services/oauthService.ts
소셜 유저 가입 시 nickname으로 저장되도록 설정
> [안재민] 소셜유저 가입 nickname 설정

- src/controllers/quoteController.ts
- src/controllers/reviewController.ts
- src/repositorys/quoteRepository.ts
- src/services/quoteService.ts
> [강범준] (기사님이 작성한) 견적서 상세 조회 cost 쿼리 삭제

- src/middlewares/authMiddleware.ts
- src/services/authService.ts
- src/services/reviewService.ts
- src/utils/constructors/httpError.ts
- src/utils/constructors/redirectError.ts
- 기존의 moverId 에서 moverId와 confirmedQuoteId로 변경
- 기존의 에러 핸들링에서 interface의 활용은 코드가 길어짐 class constructor 관리
> [탁우현] 리뷰작성 가능, 에러 처리 개선

- src/controllers/authController.ts
- src/controllers/oauthController.ts
- src/middlewares/passport.ts
- src/schedules/images.ts
- src/services/authService.ts
- src/services/customerService.ts
- src/services/moverService.ts
- src/services/userService.ts
- src/utils/constructors/httpError.ts
- src/utils/s3.utils.ts
- 인증, 유저, 고객, 무버, 이미지업로드, passport 적용
- 일부 컨트롤러에서 에러처리 하는 부분 서비스로 이동
- httpError : case 409 conflict 추가
- passport 에서는 done()에서 throw를 하기때문에 아래와 같이 HttpError 사용
```
if (!token) {
return done(new HttpError(403, "토큰이 존재하지 않습니다."), false);
}
```
> [안재민] httpError, redirectError 적용

- src/middlewares/validations/movingRequest.ts
- src/repositorys/moverRepository.ts
- src/repositorys/movingRequestRepository.ts
- src/schedules/notifications.ts
- src/services/confirmedQuoteService.ts
- src/services/customerService.ts
- src/services/moverService.ts
- src/services/movingRequestService.ts
- src/services/notificationService.ts
- src/services/quoteService.ts
- 리스폰스 에러 핸들링시 반복되는 에러 객체생성을 class constructor로 처리
- 프론트 알림 렌더링시 색변경을 위한 구분자 추가
- 이사 요청 생성시 당일 날짜의 이사 요청은 에러 반환
> [탁우현] ♻️ [리팩토링] : 에러 constructor 사용

- src/controllers/quoteController.ts
- src/controllers/reviewController.ts
- src/middlewares/uploadFile.ts
- src/repositorys/quoteRepository.ts
- src/repositorys/reviewRepository.ts
- src/services/quoteService.ts
- src/services/reviewService.ts
- src/utils/review/types.ts
- multer를 사용한 이미지 파일 업로드 처리 (최대 3개)
- S3 업로드 로직 연결
- 이미지 업로드 에러 처리 추가
요청 : body에 comment 추가
응답 : 요청(comment)로 응답의 comment 작성
데이터 관리 : quote 테이블을 이용해 반려 정보를 관리한다면, 반려에 사용한 comment도 quote의 comment column에 저장
> [강범준] :sparkles:[Feat]리뷰 작성 시 이미지 파일 처리 로직 구현 & comment 기능 수정

- src/controllers/authController.ts
- src/controllers/customerController.ts
- src/controllers/moverController.ts
- src/middlewares/uploadFile.ts
- src/repositorys/userRepository.ts
- src/services/authService.ts
- src/services/customerService.ts
- src/services/moverService.ts
- src/utils/s3.utils.ts
- uploadFiles : 이미지 배열의 길이가 0일 경우 이미지 파일 없다는 에러 스로우(이미지 개수 제한이 있다면 말씀해주세요! 에러처리 추가하겠습니다.)
- uploadOptionalFiles : 프로필 수정에 사용, 이미지가 없다면 로직수행하지않고 통과
- 단일 파일의 경우(회원가입, 프로필 등록, 수정) 컨트롤러에서 배열로 서비스에 전달, 서비스에서 [0]으로 레포지토리로 전달
- ## _리뷰 컨트롤러 이미지업로드 부분 먼저 작업부탁드립니다. 제 PR만 머지되면 리뷰쪽에서 에러떠서 dev 또는 build가 안됩니다. 같이 머지되어야 할 것 같습니다._
- 컨트롤러 미들웨어 배치 및 흐름입니다. 주석부분 참고부탁드립니다.
```
router.post(
"/signup/customer",
upload.array("imageUrl"),
uploadFiles, // 여기서 이미지 업로드 후 반환된 url을 배열에 담아 req.fileUrls에 넣어줌
asyncHandle(async (req, res, next) => {
try {
const signUpCustomer: SignUpCustomer = {
...req.body,
imageUrl: req.fileUrls, // ex) [url1, url2, url3]
services: JSON.parse(req.body.services).map(Number),
regions: JSON.parse(req.body.regions).map(Number),
isOAuth: req.body.isOAuth === "true",
};
await …
```
> [안재민] 이미지 업로드 미들웨어로 변경 및 적용

- src/controllers/quoteController.ts
- src/controllers/reviewController.ts
- src/middlewares/validations/quote.ts
- src/repositorys/movingRequestRepository.ts
- src/services/movingRequestService.ts
- src/services/quoteService.ts
- src/services/regionService.ts
- src/services/serviceService.ts
- isquote가 undefined count 불일치 기본 false로 변경 지정견적 조건부 isPastRequest 따라 변경 또한 견적이 확전된 건은 제외
- 프로젝트 전체 코드 에러반환 httpError constructor로 변경
> [탁우현] 프론트 요청 및 리팩토링

- src/repositorys/movingRequestRepository.ts
- src/services/movingRequestService.ts
- 지정요청전에 기사가 일반견적을 작성했다면 받은 일반 견적이 있다는 메시지 반환
> [탁우현]  기사 지정시 일반견적 확인
